AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda template
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  SamDemoFunction: # your app function
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: torchlambda
      Runtime: provided
      MemorySize: 256
      Events:
        Gateway:
          Type: Api
          Properties:
            Path: /app
            Method: post
      Environment:
        Variables:
           k1: "v1"
           k2: "v2"
      Layers:
        - !Ref ModelLayer
    Metadata:
      BuildMethod: makefile
    
  ModelLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: .
    Metadata:
      BuildMethod: makefile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SamDemoApi:
    Description: "API Gateway endpoint URL for Prod stage for app function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/app/" 
  SamDemoFunction:
    Description: "App Lambda Function ARN"
    Value: !GetAtt SamDemoFunction.Arn
